
export default {
    MENU_MOUNT: 'MENU_MOUNT',
    MENU_TOGGLE: 'MENU_TOGGLE',
    MENU_LOADED: 'MENU_LOADED',
    MENU_ANIMATING: 'MENU_ANIMATING',
    MENU_ITEM_COLLAPSE: 'MENU_ITEM_COLLAPSE',
    MENU_ITEM_EXPAND: 'MENU_ITEM_EXPAND',
    MENU_ITEM_TOGGLE: 'MENU_ITEM_TOGGLE',
    MENU_SEARCH: 'MENU_SEARCH',
    MENU_FILTER: 'MENU_FILTER',
};
